### ISSUE TITLE
how do I pass tokens to server for authentication? 

### ISSUE THREAD

**Issue by sido420** [kiwiirc/nativescript-tus-client#5]
How do I pass tokens to server for authentication? I use headers in browser but that does not seem to be supported and looks like metadata will be removed as well. 
So whats the proposed solution?

**Comment by tralves** [comment]
Hi!

Issue #3 was a mistake. `metadata` is being used. There is also a `headers` field which I didn't add to the docs (sorry again).

I am adding it now.

Can you try again?

**Comment by sido420** [comment]
Thanks. I will try once we get the build issue resolved (see https://github.com/kiwiirc/nativescript-tus-client/issues/8)

**Comment by sido420** [comment]
This seems to work now. Thanks.
