### ISSUE TITLE
ReferenceError with NativeScript  7

### ISSUE THREAD

**Issue by kaidgii** [kiwiirc/nativescript-tus-client#9]
### Problem:
Face the Reference error with NS 7+
```
ReferenceError: TUSFileUploadStore is not defined
```
### Which platform(s) does your issue occur on?
- iOS
- iOS 14.2 
- emulator

### Please, provide the following version numbers that your issue occurs with:

- CLI: 7.0.9-rc.2
- Plugin(s):     
```
    "@nativescript-community/ui-collectionview": "4.0.10",
    "@nativescript-community/ui-image": "4.0.20",
    "@nativescript-community/ui-material-ripple": "5.1.16",
    "@nativescript/appversion": "2.0.0",
    "@nativescript/core": "7.1.4",
    "@nativescript/email": "2.0.0",
    "@nativescript/iqkeyboardmanager": "2.0.0",
    "@nativescript/localize": "5.0.2",
    "@nativescript/social-share": "2.0.1",
    "@nativescript/theme": "2.5.0",
    "@nstudio/nativescript-exoplayer": "^5.0.4",
    "@nstudio/nativescript-pulltorefresh": "3.0.1",
    "@vue/devtools": "5.3.3",
    "country-codes-list": "1.6.8",
    "google-libphonenumber": "3.2.15",
    "moment": "2.29.1",
    "nativescript-awesome-webview-with-custom-menu-items": "70.1.1",
    "nativescript-carousel": "7.0.1",
    "nativescript-checkbox-ns-7": "22.0.0",
    "nativescript-clipboard": "2.0.0",
    "nativescript-firebase-updated-new": "711.1.2",
    "nativescript-gif": "5.0.0",
    "nativescript-mediafilepicker": "^4.0.2",
    "nativescript-socketio": "3.3.1",
    "nativescript-toasty-ns-7": "14.0.0",
    "nativescript-tus-client": "^1.0.0",
    "nativescript-twitter-updated": "22.0.4",
    "nativescript-ui-autocomplete": "7.0.2",
    "nativescript-vue": "2.8.3",
    "nativescript-vue-devtools-ns-7": "11.4.0",
    "nativescript-vue-shadow-ns-7": "10.1.0",
    "nativescript-websockets": "1.5.6",
    "nativescript-windowed-modal-updated": "76.0.0",
    "nativescript-youtubeplayer-inline": "73.0.1",
    "query-string": "6.8.3",
    "toposort": "^2.0.2",
    "validator": "^10.11.0",
    "vue": "^2.6.10",
    "vue-i18n": "^8.8.0",
    "vue-truncate-filter": "^1.1.7",
    "vuex": "^3.0.1",
    "vuex-persistedstate": "^2.5.4"
```

### Please, tell us how to recreate the issue in as much detail as possible. 
Use it with NativeScript 7+ 

### Is there any code involved? 
```
   try {
      const MIMEType = videoName.substring(videoName.lastIndexOf('.') + 1)
      const firebaseAuthToken = await Firebase.getAuthToken()
      
      const upload = new tus.Upload(video, {
        endpoint: videoUploadEndpoint,
        metadata: {
          filename: `user_video.${MIMEType}`,
          filetype: `video/${MIMEType}`
        },
        headers: {
          Authorization: `Bearer ${firebaseAuthToken}`
        },
        onError: (error) => {
          console.log(`Failed because:  ${error}`)
        },
        onProgress: (bytesUploaded, bytesTotal) => {
          console.log((bytesUploaded / bytesTotal * 100).toFixed(2))
        },
        onSuccess: () => {
          console.log('Success')
        }
      })
      
      upload.start()
   } catch (error) {
      console.log(error)
   }
```

**Comment by tralves** [comment]
Hi!

Just tested in a {N} 7 project and it works. Looks like an error loading the native lib. Try `rm -rf platforms` and try again.

**Comment by kaidgii** [comment]
@tralves Hi!
The result is the same. I run `ns clean` and `rm -rf platforms`.  Nothing change, still get an error.

**Comment by tralves** [comment]
Very weird.

Open the folder `irccom-app/platforms/ios/Pods`. Do you see `TUSKit` in there? When building the app, do you see the TUSKit pod being added?

**Comment by kaidgii** [comment]
Yeap, TUSKit is present

**Comment by kaidgii** [comment]
I also created a new nativescript-vue project and test it. Got the same error. I think the problem is that it is not compatible with NS 7+ 😥
https://nativescript.org/blog/nativescript-7-for-plugin-authors/ need some updates due to this article

I will fork and try to help you with updating. Pls make me a contributor

**Comment by tralves** [comment]
Hi!

It's weird because it's working here, on my NS 7.1 project.
I appreciate if you want to look at it, as I can't right now. I don't need to make you a contributor. You can fork and PR later.

**Comment by kaidgii** [comment]
Your NS 7.1 project is a plain js/ts project?

**Comment by tralves** [comment]
Is NS-Vue...

This is very weird. Since the pod is there, NS should be able to detect `TUSFileUploadStore`.
I can just put a breakpoint somewhere with the chrome dev tools and type `TUSFileUploadStore` in the console. It returns the object.

**Comment by tralves** [comment]
Btw, try upgrading your NC-cli. I am on 7.2.0 here.

**Comment by kaidgii** [comment]
Okay, I will test with NS 7.2

**Comment by tralves** [comment]
BTW, I just created a brand new NS-Vue project with the plugin and... it worked...

Here's the repo: https://github.com/tralves/tus-test

**Comment by kaidgii** [comment]
Well, it is very weird. I have updated NS to 7.2 on the other computer, clone your repo and face the same error: 
`TUSFileUploadStore is not defined`

**Comment by kaidgii** [comment]
My `ns info` output:
`✔ Component nativescript has 7.2.0 version and is up to date.
 ✔ Component @nativescript/ios has 7.2.0 version and is up to date.
`

**Comment by romandragan** [comment]
@tralves, actually I have the same issue. What `TUSKit` Pod version are you using? Mine is `2.0.0`. My assumption here is that you're using some more older one, like `2.1.5.alpha`, `2.1.3.alpha` etc. Will try those on my side.

**Comment by tralves** [comment]
Hum, that thought occurred to me, but then I forgot to test it. That's very
likely the cause of the problem.
I'll see what I can do too.

**Comment by romandragan** [comment]
@tralves, it should be set to `pod 'TUSKit', '~> 1.4.2'` as this is the latest version with `TUSFileUploadStore.h/m`files present: `https://github.com/tus/TUSKit/tree/1.4.2/TUSKit`.

**Comment by tralves** [comment]
Updated the npm package. The new version, 1.0.1, should be fixed.
Please test and see if it works, @romandragan , @kaidgii. Sorry for not detecting this sooner. It was using the cached pod here.
Oh, `rm -rf platforms` or `ns clean` after updating the package.

**Comment by romandrahan** [comment]
@tralves, thanks. Adding `pod 'TUSKit', '~> 1.4.2'` to project's `app/App_Resources/iOS/Podfile` worked for me even with 1.0.0 plugin version. So more likely it will be fine with 1.0.1 as well.
